# Use a Java 17 base image
FROM adoptopenjdk/openjdk17:alpine-jre

# Set working directory
WORKDIR /app

# Copy build files to container
COPY build/libs/*.jar app.jar

# Expose port 8080
EXPOSE 8080

# Start the Spring Boot application
ENTRYPOINT ["java", "-jar", "app.jar"]